//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidUsbSerialAssistant.Resx {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AndroidUsbSerialAssistant.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Altitude 的本地化字符串。
        /// </summary>
        public static string Altitude {
            get {
                return ResourceManager.GetString("Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Baud Rate 的本地化字符串。
        /// </summary>
        public static string Baud_Rate {
            get {
                return ResourceManager.GetString("Baud Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chat 的本地化字符串。
        /// </summary>
        public static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Bits 的本地化字符串。
        /// </summary>
        public static string Data_Bits {
            get {
                return ResourceManager.GetString("Data Bits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device has detached 的本地化字符串。
        /// </summary>
        public static string Device_Detached {
            get {
                return ResourceManager.GetString("Device Detached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Favour 的本地化字符串。
        /// </summary>
        public static string Favour {
            get {
                return ResourceManager.GetString("Favour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Favour Message 的本地化字符串。
        /// </summary>
        public static string FavourMessage {
            get {
                return ResourceManager.GetString("FavourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frequency 的本地化字符串。
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get location failed 的本地化字符串。
        /// </summary>
        public static string Get_Location_Failed {
            get {
                return ResourceManager.GetString("Get Location Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex 的本地化字符串。
        /// </summary>
        public static string Hex {
            get {
                return ResourceManager.GetString("Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device has attached and ready to use 的本地化字符串。
        /// </summary>
        public static string Known_Device {
            get {
                return ResourceManager.GetString("Known Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Latitude 的本地化字符串。
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Longitude 的本地化字符串。
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device not found 的本地化字符串。
        /// </summary>
        public static string No_Device {
            get {
                return ResourceManager.GetString("No Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specific driver not found 的本地化字符串。
        /// </summary>
        public static string No_Driver {
            get {
                return ResourceManager.GetString("No Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please allow this software to access the USB device 的本地化字符串。
        /// </summary>
        public static string No_Permission {
            get {
                return ResourceManager.GetString("No Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error opening device 的本地化字符串。
        /// </summary>
        public static string Open_Failed {
            get {
                return ResourceManager.GetString("Open Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parity 的本地化字符串。
        /// </summary>
        public static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause 的本地化字符串。
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port has been closed 的本地化字符串。
        /// </summary>
        public static string Port_Closed {
            get {
                return ResourceManager.GetString("Port Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error occurred when closing port! 的本地化字符串。
        /// </summary>
        public static string Port_Closed_Error {
            get {
                return ResourceManager.GetString("Port Closed Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port listening... 的本地化字符串。
        /// </summary>
        public static string Port_Listening {
            get {
                return ResourceManager.GetString("Port Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Received 的本地化字符串。
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data received error 的本地化字符串。
        /// </summary>
        public static string Received_Error {
            get {
                return ResourceManager.GetString("Received Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings save failed! 的本地化字符串。
        /// </summary>
        public static string Save_Failed {
            get {
                return ResourceManager.GetString("Save Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings saved 的本地化字符串。
        /// </summary>
        public static string Save_Success {
            get {
                return ResourceManager.GetString("Save Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Failed 的本地化字符串。
        /// </summary>
        public static string Send_Error {
            get {
                return ResourceManager.GetString("Send Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sent 的本地化字符串。
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Send Started 的本地化字符串。
        /// </summary>
        public static string Start_Auto_Send {
            get {
                return ResourceManager.GetString("Start Auto Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Send Stopped 的本地化字符串。
        /// </summary>
        public static string Stop_Auto_Send {
            get {
                return ResourceManager.GetString("Stop Auto Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Bits 的本地化字符串。
        /// </summary>
        public static string Stop_Bits {
            get {
                return ResourceManager.GetString("Stop Bits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support Devices 的本地化字符串。
        /// </summary>
        public static string Support_Devices {
            get {
                return ResourceManager.GetString("Support Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown device has attached 的本地化字符串。
        /// </summary>
        public static string Unknown_Device {
            get {
                return ResourceManager.GetString("Unknown Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Write data failed! 的本地化字符串。
        /// </summary>
        public static string Write_Failed {
            get {
                return ResourceManager.GetString("Write Failed", resourceCulture);
            }
        }
    }
}
